export const INSERT_IMAGE_LINK = 'INSERT_IMAGE_LINK';
export const INSERT_EMAIL = 'INSERT_EMAIL';
export const INSERT_PASS = 'INSERT_PASS';
export const INSERT_NAME_REGISTER = 'INSERT_NAME_REGISTER';
export const INSERT_EMAIL_REGISTER = 'INSERT_EMAIL_REGISTER';
export const INSERT_PASS_REGISTER = 'INSERT_PASS_REGISTER';